### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by nicolastakashi** [Flepper/flepper#36]
## Expected Behavior
It would be interesting if it had an API to perform Soft Delete from the records instead of a real delete.

For example:

```
FlepperQueryBuilder.SoftDelete()
                .From("user")
                .Where("Id",1);
```
To know which field is used to mark the record as deleted, we can use a configuration class so that we do not have to inform all that we have to use this feature.

## Actual Behavior
Functionality not implemented

**Comment by kidchenko** [comment]
I am ready to start working in this issue. :)

**Comment by nicolastakashi** [comment]
@kidchenko awesome.

Just to help you, internally we think about create a class to convention over configuration. Where the user can configure which field in your model represents soft delete.

**Comment by kidchenko** [comment]
I am just reporting that I am still working in this feature, I want to open a discussion on the maintainer team about how you think implement the configuration.

**Comment by nicolastakashi** [comment]
Ok @kidchenko!
We just thinking about create a class to convention over configuration, where the user can configure wihch field in your model represents soft delete.

**Comment by nicolastakashi** [comment]
Hi @kidchenko some news about that?

**Comment by gustavoferrazfontes** [comment]
Hi! 
I did an implementation that cover this feature. My next goal now is going to do the implementation in dapper extensions.

**Comment by gustavoferrazfontes** [comment]
implemented.
