### ISSUE TITLE
Nuget package can not be found

### ISSUE THREAD

**Issue by rafakwolf** [Flepper/flepper#47]
## Expected Behavior
A description of the expected behavior

## Actual Behavior
Description of current behavior
When i search for "Flepper" package on nuget, nothing is found
## Steps to Reproduce the Problem

  1. 
  1.
  1.

**Comment by rafakwolf** [comment]
My bad! searching in a different nuget source

**Comment by AlbertoMonteiro** [comment]
No @rafakwolf 

https://www.nuget.org/packages?q=Flepper
