### ISSUE TITLE
No LIKE ???

### ISSUE THREAD

**Issue by netdragoon** [Flepper/flepper#57]
## Expected Behavior

```
FlepperQueryBuilder.Select().From("table").Where("field").Contains("value");
FlepperQueryBuilder.Select().From("table").Where("field").StartsWith("value");
FlepperQueryBuilder.Select().From("table").Where("field").EndsWith("value");
```

## Actual Behavior

Does not exist !!!!

## Steps to Reproduce the Problem

  1. Like Filter is not present and does not generate the expected SQL

**Comment by gustavoferrazfontes** [comment]
@netdragoon  
We would be grateful if you could open a PR with this feature 😄

**Comment by netdragoon** [comment]
Pull Request -> https://github.com/Flepper/flepper/pull/60

**Comment by netdragoon** [comment]
Add Contains, StartsWith, EndsWith and Between: https://github.com/Flepper/flepper/pull/60
