### ISSUE TITLE
Problem Field with Nullable Type?

### ISSUE THREAD

**Issue by fulviocanducci** [Flepper/flepper#79]
## Expected Behavior

**Table**:

![table](https://user-images.githubusercontent.com/25593291/31916847-67aea1f0-b833-11e7-902b-e307f66fc1ee.png)

In the **code**:

```
     dbConnection
                    .Insert()
                    .Into("Owe")
                    .Columns("Created", "Name", "Active")
                    .Values(null, Guid.NewGuid().ToString(), true)
                    .Execute();
```

## Actual Behavior

Can not write `NULL` value to fields that can receive this value type?

## Steps to Reproduce the Problem

```
IDbConnection dbConnection = new SqlConnection("....")
dbConnection
            .Insert()
            .Into("Owe")
             .Columns("Created", "Name", "Active")
             .Values(null, Guid.NewGuid().ToString(), true)
             .Execute();
```

**Exception**

> CloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
>    at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
>    at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
>    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
>    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
>    at Flepper.QueryBuilder.DapperExtensions.FlepperDapperQuery.Execute(IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
>    at Flepper.QueryBuilder.DapperExtensions.QueryBuilderExtensions.Execute(IQueryCommand queryCommand, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
>    at ConsoleApp33.Program.Main(String[] args) in C:\Users\Developer\Documents\Visual Studio 2017\Projects\ConsoleApp33\ConsoleApp33\Program.cs:line 32
> ClientConnectionId:64eb31fb-9124-45b1-b139-7ae23c22072c
> Error Number:257,State:3,Class:16

### The exception happens because of the `NULL` pass, which should be a problem, but then what value do I have to pass to symbolize [DateTime?](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/nullable-types/) or any type ([`Nullable<>`](https://docs.microsoft.com/pt-br/dotnet/csharp/programming-guide/nullable-types/)) Maybe a constant for later testing??

Line of problem:

https://github.com/Flepper/flepper/blob/development/Flepper.QueryBuilder/Utils/ParameterObjectBuilder.cs#L46

Code line of problem
```
CreateProperty(typeBuilder, parameter.Key.Replace("@", ""), 
            parameter.Value is null 
                 ? typeof(object)
                 : parameter.Value.GetType());
```

Specific problem 

```
typeof(object) 
```

**Comment by nicolastakashi** [comment]
Hi @fulviocanducci, thank you for your contribution.

We already resolve this issue in #70, this will be available in next release

**Comment by fulviocanducci** [comment]
@nicolastakashi Wonderfull !!!

**Comment by nicolastakashi** [comment]
@fulviocanducci ai Will Create integration test to cover this, If you want you can do that...

Just let me know

**Comment by fulviocanducci** [comment]
@nicolastakashi 
What I thought of doing would be a class that could be used to differentiate those that are null but, need to specify the type, what do you think?

**Comment by ctyar** [comment]
@nicolastakashi I'm using this library in a project and this issue is blocking us.
I'm ready to work on this issue and send a PR as soon as possible.
I just need some points on how are we going to fix this.
I already have read the code and understood the problem.

**Comment by fulviocanducci** [comment]
@ctyar 
test the problem so I can compare!

**Comment by ctyar** [comment]
@fulviocanducci I'm sending a `null` value for a `Nullable<Guid>` column to `FlepperDapperQuery.Execute` method and receiving this exception:
`Implicit conversion from data type sql_variant to uniqueidentifier is not allowed. Use the CONVERT function to run this query.'`

**Comment by fulviocanducci** [comment]
@ctyar 


As I already reported in the problem is in that snippet of code, where the type was decided as `object` and is wrong?

```
CreateProperty(typeBuilder, parameter.Key.Replace("@", ""), 
            parameter.Value is null 
                 ? typeof(object)
                 : parameter.Value.GetType());
```
Send a PR !!!

**Comment by ctyar** [comment]
@fulviocanducci You are right.
We need to somehow get the actual type there instead of `typeof(object)`.
The problem is we don't have that information there(as we are getting the type from the values).
I think we have to get the types where we are introducing the column names but that's a big change that's why I asked @nicolastakashi's opinion.

**Comment by AlbertoMonteiro** [comment]
When you send NULL as one of the parameters in Value method, turn impossible to know what type it is, so we decided to use object.

One solution would be instead passing null, use something like that

`FlepperQueryBuilder.NullValue<DateTime?>()`

```csharp
dbConnection
    .Insert()
    .Into("Owe")
    .Columns("Created", "Name", "Active")
    .Values(FlepperQueryBuilder.NullValue<DateTime?>(), Guid.NewGuid().ToString(), true)
    .Execute();
```

Then in parameters creation, we could check if the type is a FlepperNullValue and use the right type.

**Comment by fulviocanducci** [comment]
@AlbertoMonteiro @ctyar 

Pull Request https://github.com/Flepper/flepper/pull/90

**Comment by fulviocanducci** [comment]
Merged https://github.com/Flepper/flepper/pull/90
