### ISSUE TITLE
Cannot pass an array of column names to Columns method

### ISSUE THREAD

**Issue by ctyar** [Flepper/flepper#85]
## Expected Behavior
It should be possible to pass an array of column names to `Columns` method while inserting a row.

## Actual Behavior
Passing an array is not possible:
```
Argument 1: cannot convert from 'string[]' to 'Flepper.QueryBuilder.SqlColumn'
```
and `SqlColumn` constructor is internal so it's not possible to create an array of that too.

## Steps to Reproduce the Problem

Create an array of column names and pass it to the `Columns` method:
```
var columnNames = new[] {"Column1", "Column2", "Column3"};

Connection.Insert().Into("Table1").Columns(columnNames).Values("Value1", "Value2", "Value3").Execute();
```

**Comment by ctyar** [comment]
In case you consider this as a bug or even an improvement to APIs I can submit a PR

**Comment by nicolastakashi** [comment]
Hi @ctyar, thank you for open a issue.

I believe that is a API improvement, So if you want my friend you can send a PR, just let us know if you send or not 

Thank you for your contribution.

**Comment by ctyar** [comment]
Hi @nicolastakashi 
I will send the PR for sure. The design I have in mind is as follows:

For `IInsertIntoCommand`:

    IInsertIntoCommand Columns(IEnumerable<string> columns);

and for `ISelectCommand`:

    ISelectCommand SelectCommand(IEnumerable<string> columns);

and implementing the new tests that we need.
If these changes are ok with you I will start.

**Comment by AlbertoMonteiro** [comment]
@ctyar consider use this:

For `IInsertIntoCommand`:

    IInsertIntoCommand Columns(params string[] columns);

and for `ISelectCommand`:

    ISelectCommand SelectCommand(params string[] columns);
